# ================================================================================
# ========== WELCOME TO THE NEOCOMPILER ECO NEO BLOCKCHAIN MICROSERVICE  =========
# ================================================================================

version: "3.7"
services:

# ================================================================================
# ================== OPEN CONTAINER WITH Neo.CLI RPC DESIGNED FOR MAINNET ========
  eco-neo-csharp-noderpc-mainnet-running:
    image: eco-neo-csharp-simple-node:latest
    container_name: "eco-neo-csharp-noderpc-${NETWORK}"
    # privileged is needed for controlling ifconfig
    privileged: true
    ports: 
      - "${PORT_BEGIN}0334:${PORT_BEGIN}0334"
      - "${PORT_BEGIN}0333:${PORT_BEGIN}0333"
      - "${PORT_BEGIN}0332:${PORT_BEGIN}0332"
    volumes:
      - ./Neo.CLI/configs/config.${NETWORK}.json:/opt/node/Neo.CLI/config.json
      - ./Neo.CLI/configs/plugins/appLogConfig.json:/opt/node/Neo.CLI/Plugins/ApplicationLogs/ApplicationLogs.json
      - ./Neo.CLI/configs/plugins/rpcServer.json:/opt/node/Neo.CLI/Plugins/RpcServer/RpcServer.json    
      - ./Neo.CLI/configs/plugins/tokensTracker.json:/opt/node/Neo.CLI/Plugins/TokensTracker/TokensTracker.json
      - ./Neo.CLI/configs/plugins/storageDumper.json:/opt/node/Neo.CLI/Plugins/StatesDumper/StorageDumper.json   
      - ./Neo.CLI/configs/plugins/stateService.json:/opt/node/Neo.CLI/Plugins/StateService/StateService.json
      - ./Neo.CLI/configs/plugins/wallets/walletRpc.json:/opt/node/Neo.CLI/walletRpc.json   
      - ./Neo.CLI/configs/plugins/getIncStorage.sh:/opt/getIncStorage.sh
      - ./Chain_$NETWORK:/opt/node/Neo.CLI/Chain_${FOLDER_BEGIN}746E41
      - ./AppLog_$NETWORK:/opt/node/Neo.CLI/ApplicationLogs_0000DDB1
      - ./Storage_$NETWORK:/opt/node/Neo.CLI/Storage
      - ./chain.acc.zip:/opt/node/Neo.CLI/chain.acc.zip
    environment:
      IS_CONSENSUS: 0
      IS_RPC: 1
      NUMBER_SERVER: 1
      DISABLE_NETWORK_P2P: 0
    healthcheck:
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/${PORT_BEGIN}0333
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
# ================================================================================
# ======================= THANKS FOR CREATING ME =================================
# ================================================================================
